/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccordDeSousTraitanceRouteImport } from './routes/accord-de-sous-traitance'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as ConditionsGeneralesRouteImport } from './routes/conditions-generales'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as NouveauMotDePasseRouteImport } from './routes/nouveau-mot-de-passe'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppClientsRouteImport } from './routes/app/clients'
import { Route as AppCompteRouteImport } from './routes/app/compte'
import { Route as AppDebiteursRouteImport } from './routes/app/debiteurs'
import { Route as AppImportFacturesRouteImport } from './routes/app/import-factures'
import { Route as AppProceduresRouteImport } from './routes/app/procedures'
import { Route as AppRevelationRouteImport } from './routes/app/revelation'
import { Route as RejoindreTokenRouteImport } from './routes/rejoindre.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppArretIdRouteImport } from './routes/app/arret.$id'
import { Route as AppClientsIdRouteImport } from './routes/app/clients.$id'
import { Route as AppCreanceIdRouteImport } from './routes/app/creance.$id'
import { Route as AppDebiteursIdRouteImport } from './routes/app/debiteurs.$id'
import { Route as AppDecompteIdRouteImport } from './routes/app/decompte.$id'
import { Route as AppDossierIdRouteImport } from './routes/app/dossier.$id'
import { Route as AppImportFacturesIdRouteImport } from './routes/app/import-factures.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordDeSousTraitanceRoute = AccordDeSousTraitanceRouteImport.update({
  id: '/accord-de-sous-traitance',
  path: '/accord-de-sous-traitance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesRoute = ConditionsGeneralesRouteImport.update({
  id: '/conditions-generales',
  path: '/conditions-generales',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveauMotDePasseRoute = NouveauMotDePasseRouteImport.update({
  id: '/nouveau-mot-de-passe',
  path: '/nouveau-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompteRoute = AppCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDebiteursRoute = AppDebiteursRouteImport.update({
  id: '/debiteurs',
  path: '/debiteurs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportFacturesRoute = AppImportFacturesRouteImport.update({
  id: '/import-factures',
  path: '/import-factures',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProceduresRoute = AppProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRevelationRoute = AppRevelationRouteImport.update({
  id: '/revelation',
  path: '/revelation',
  getParentRoute: () => AppRouteRoute,
} as any)
const RejoindreTokenRoute = RejoindreTokenRouteImport.update({
  id: '/rejoindre/$token',
  path: '/rejoindre/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArretIdRoute = AppArretIdRouteImport.update({
  id: '/arret/$id',
  path: '/arret/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppCreanceIdRoute = AppCreanceIdRouteImport.update({
  id: '/creance/$id',
  path: '/creance/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDebiteursIdRoute = AppDebiteursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDebiteursRoute,
} as any)
const AppDecompteIdRoute = AppDecompteIdRouteImport.update({
  id: '/decompte/$id',
  path: '/decompte/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDossierIdRoute = AppDossierIdRouteImport.update({
  id: '/dossier/$id',
  path: '/dossier/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportFacturesIdRoute = AppImportFacturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppImportFacturesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/accord-de-sous-traitance': typeof AccordDeSousTraitanceRoute
  '/bienvenue': typeof BienvenueRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/showroom': typeof ShowroomRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/compte': typeof AppCompteRoute
  '/app/debiteurs': typeof AppDebiteursRouteWithChildren
  '/app/import-factures': typeof AppImportFacturesRouteWithChildren
  '/app/procedures': typeof AppProceduresRoute
  '/app/revelation': typeof AppRevelationRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/arret/$id': typeof AppArretIdRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/creance/$id': typeof AppCreanceIdRoute
  '/app/debiteurs/$id': typeof AppDebiteursIdRoute
  '/app/decompte/$id': typeof AppDecompteIdRoute
  '/app/dossier/$id': typeof AppDossierIdRoute
  '/app/import-factures/$id': typeof AppImportFacturesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accord-de-sous-traitance': typeof AccordDeSousTraitanceRoute
  '/bienvenue': typeof BienvenueRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/showroom': typeof ShowroomRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/compte': typeof AppCompteRoute
  '/app/debiteurs': typeof AppDebiteursRouteWithChildren
  '/app/import-factures': typeof AppImportFacturesRouteWithChildren
  '/app/procedures': typeof AppProceduresRoute
  '/app/revelation': typeof AppRevelationRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/arret/$id': typeof AppArretIdRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/creance/$id': typeof AppCreanceIdRoute
  '/app/debiteurs/$id': typeof AppDebiteursIdRoute
  '/app/decompte/$id': typeof AppDecompteIdRoute
  '/app/dossier/$id': typeof AppDossierIdRoute
  '/app/import-factures/$id': typeof AppImportFacturesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/accord-de-sous-traitance': typeof AccordDeSousTraitanceRoute
  '/bienvenue': typeof BienvenueRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/showroom': typeof ShowroomRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/compte': typeof AppCompteRoute
  '/app/debiteurs': typeof AppDebiteursRouteWithChildren
  '/app/import-factures': typeof AppImportFacturesRouteWithChildren
  '/app/procedures': typeof AppProceduresRoute
  '/app/revelation': typeof AppRevelationRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/arret/$id': typeof AppArretIdRoute
  '/app/clients/$id': typeof AppClientsIdRoute
  '/app/creance/$id': typeof AppCreanceIdRoute
  '/app/debiteurs/$id': typeof AppDebiteursIdRoute
  '/app/decompte/$id': typeof AppDecompteIdRoute
  '/app/dossier/$id': typeof AppDossierIdRoute
  '/app/import-factures/$id': typeof AppImportFacturesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/accord-de-sous-traitance'
    | '/bienvenue'
    | '/conditions-generales'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/politique-de-confidentialite'
    | '/showroom'
    | '/app/clients'
    | '/app/compte'
    | '/app/debiteurs'
    | '/app/import-factures'
    | '/app/procedures'
    | '/app/revelation'
    | '/rejoindre/$token'
    | '/app/'
    | '/api/auth/$'
    | '/app/arret/$id'
    | '/app/clients/$id'
    | '/app/creance/$id'
    | '/app/debiteurs/$id'
    | '/app/decompte/$id'
    | '/app/dossier/$id'
    | '/app/import-factures/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accord-de-sous-traitance'
    | '/bienvenue'
    | '/conditions-generales'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/politique-de-confidentialite'
    | '/showroom'
    | '/app/clients'
    | '/app/compte'
    | '/app/debiteurs'
    | '/app/import-factures'
    | '/app/procedures'
    | '/app/revelation'
    | '/rejoindre/$token'
    | '/app'
    | '/api/auth/$'
    | '/app/arret/$id'
    | '/app/clients/$id'
    | '/app/creance/$id'
    | '/app/debiteurs/$id'
    | '/app/decompte/$id'
    | '/app/dossier/$id'
    | '/app/import-factures/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/accord-de-sous-traitance'
    | '/bienvenue'
    | '/conditions-generales'
    | '/connexion'
    | '/inscription'
    | '/mentions-legales'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/politique-de-confidentialite'
    | '/showroom'
    | '/app/clients'
    | '/app/compte'
    | '/app/debiteurs'
    | '/app/import-factures'
    | '/app/procedures'
    | '/app/revelation'
    | '/rejoindre/$token'
    | '/app/'
    | '/api/auth/$'
    | '/app/arret/$id'
    | '/app/clients/$id'
    | '/app/creance/$id'
    | '/app/debiteurs/$id'
    | '/app/decompte/$id'
    | '/app/dossier/$id'
    | '/app/import-factures/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AccordDeSousTraitanceRoute: typeof AccordDeSousTraitanceRoute
  BienvenueRoute: typeof BienvenueRoute
  ConditionsGeneralesRoute: typeof ConditionsGeneralesRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NouveauMotDePasseRoute: typeof NouveauMotDePasseRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  ShowroomRoute: typeof ShowroomRoute
  RejoindreTokenRoute: typeof RejoindreTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accord-de-sous-traitance': {
      id: '/accord-de-sous-traitance'
      path: '/accord-de-sous-traitance'
      fullPath: '/accord-de-sous-traitance'
      preLoaderRoute: typeof AccordDeSousTraitanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales': {
      id: '/conditions-generales'
      path: '/conditions-generales'
      fullPath: '/conditions-generales'
      preLoaderRoute: typeof ConditionsGeneralesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveau-mot-de-passe': {
      id: '/nouveau-mot-de-passe'
      path: '/nouveau-mot-de-passe'
      fullPath: '/nouveau-mot-de-passe'
      preLoaderRoute: typeof NouveauMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/compte': {
      id: '/app/compte'
      path: '/compte'
      fullPath: '/app/compte'
      preLoaderRoute: typeof AppCompteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/debiteurs': {
      id: '/app/debiteurs'
      path: '/debiteurs'
      fullPath: '/app/debiteurs'
      preLoaderRoute: typeof AppDebiteursRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import-factures': {
      id: '/app/import-factures'
      path: '/import-factures'
      fullPath: '/app/import-factures'
      preLoaderRoute: typeof AppImportFacturesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/procedures': {
      id: '/app/procedures'
      path: '/procedures'
      fullPath: '/app/procedures'
      preLoaderRoute: typeof AppProceduresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/revelation': {
      id: '/app/revelation'
      path: '/revelation'
      fullPath: '/app/revelation'
      preLoaderRoute: typeof AppRevelationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/rejoindre/$token': {
      id: '/rejoindre/$token'
      path: '/rejoindre/$token'
      fullPath: '/rejoindre/$token'
      preLoaderRoute: typeof RejoindreTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/arret/$id': {
      id: '/app/arret/$id'
      path: '/arret/$id'
      fullPath: '/app/arret/$id'
      preLoaderRoute: typeof AppArretIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clients/$id': {
      id: '/app/clients/$id'
      path: '/$id'
      fullPath: '/app/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/creance/$id': {
      id: '/app/creance/$id'
      path: '/creance/$id'
      fullPath: '/app/creance/$id'
      preLoaderRoute: typeof AppCreanceIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/debiteurs/$id': {
      id: '/app/debiteurs/$id'
      path: '/$id'
      fullPath: '/app/debiteurs/$id'
      preLoaderRoute: typeof AppDebiteursIdRouteImport
      parentRoute: typeof AppDebiteursRoute
    }
    '/app/decompte/$id': {
      id: '/app/decompte/$id'
      path: '/decompte/$id'
      fullPath: '/app/decompte/$id'
      preLoaderRoute: typeof AppDecompteIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dossier/$id': {
      id: '/app/dossier/$id'
      path: '/dossier/$id'
      fullPath: '/app/dossier/$id'
      preLoaderRoute: typeof AppDossierIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import-factures/$id': {
      id: '/app/import-factures/$id'
      path: '/$id'
      fullPath: '/app/import-factures/$id'
      preLoaderRoute: typeof AppImportFacturesIdRouteImport
      parentRoute: typeof AppImportFacturesRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsIdRoute: typeof AppClientsIdRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsIdRoute: AppClientsIdRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppDebiteursRouteChildren {
  AppDebiteursIdRoute: typeof AppDebiteursIdRoute
}

const AppDebiteursRouteChildren: AppDebiteursRouteChildren = {
  AppDebiteursIdRoute: AppDebiteursIdRoute,
}

const AppDebiteursRouteWithChildren = AppDebiteursRoute._addFileChildren(
  AppDebiteursRouteChildren,
)

interface AppImportFacturesRouteChildren {
  AppImportFacturesIdRoute: typeof AppImportFacturesIdRoute
}

const AppImportFacturesRouteChildren: AppImportFacturesRouteChildren = {
  AppImportFacturesIdRoute: AppImportFacturesIdRoute,
}

const AppImportFacturesRouteWithChildren =
  AppImportFacturesRoute._addFileChildren(AppImportFacturesRouteChildren)

interface AppRouteRouteChildren {
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppCompteRoute: typeof AppCompteRoute
  AppDebiteursRoute: typeof AppDebiteursRouteWithChildren
  AppImportFacturesRoute: typeof AppImportFacturesRouteWithChildren
  AppProceduresRoute: typeof AppProceduresRoute
  AppRevelationRoute: typeof AppRevelationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArretIdRoute: typeof AppArretIdRoute
  AppCreanceIdRoute: typeof AppCreanceIdRoute
  AppDecompteIdRoute: typeof AppDecompteIdRoute
  AppDossierIdRoute: typeof AppDossierIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClientsRoute: AppClientsRouteWithChildren,
  AppCompteRoute: AppCompteRoute,
  AppDebiteursRoute: AppDebiteursRouteWithChildren,
  AppImportFacturesRoute: AppImportFacturesRouteWithChildren,
  AppProceduresRoute: AppProceduresRoute,
  AppRevelationRoute: AppRevelationRoute,
  AppIndexRoute: AppIndexRoute,
  AppArretIdRoute: AppArretIdRoute,
  AppCreanceIdRoute: AppCreanceIdRoute,
  AppDecompteIdRoute: AppDecompteIdRoute,
  AppDossierIdRoute: AppDossierIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AccordDeSousTraitanceRoute: AccordDeSousTraitanceRoute,
  BienvenueRoute: BienvenueRoute,
  ConditionsGeneralesRoute: ConditionsGeneralesRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NouveauMotDePasseRoute: NouveauMotDePasseRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  ShowroomRoute: ShowroomRoute,
  RejoindreTokenRoute: RejoindreTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
