/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as NouveauMotDePasseRouteImport } from './routes/nouveau-mot-de-passe'
import { Route as ShowroomRouteImport } from './routes/showroom'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppReglagesRouteImport } from './routes/app/_reglages'
import { Route as AppDebiteursRouteImport } from './routes/app/debiteurs'
import { Route as AppImportFacturesRouteImport } from './routes/app/import-factures'
import { Route as AppProceduresRouteImport } from './routes/app/procedures'
import { Route as AppRevelationRouteImport } from './routes/app/revelation'
import { Route as RejoindreTokenRouteImport } from './routes/rejoindre.$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppReglagesAbonnementRouteImport } from './routes/app/_reglages.abonnement'
import { Route as AppReglagesDonneesRouteImport } from './routes/app/_reglages.donnees'
import { Route as AppReglagesEquipeRouteImport } from './routes/app/_reglages.equipe'
import { Route as AppReglagesParametresRouteImport } from './routes/app/_reglages.parametres'
import { Route as AppCreanceIdRouteImport } from './routes/app/creance.$id'
import { Route as AppDonneesSupprimerCompteRouteImport } from './routes/app/donnees_.supprimer-compte'
import { Route as AppDonneesSupprimerEtablissementRouteImport } from './routes/app/donnees_.supprimer-etablissement'
import { Route as AppImportFacturesIdRouteImport } from './routes/app/import-factures.$id'
import { Route as AppReglagesAbonnementPremierBilanRouteImport } from './routes/app/_reglages.abonnement_.premier-bilan'
import { Route as AppReglagesAbonnementSuiviRouteImport } from './routes/app/_reglages.abonnement_.suivi'
import { Route as AppReglagesDonneesExportRouteImport } from './routes/app/_reglages.donnees_.export'
import { Route as AppReglagesEquipeInviterRouteImport } from './routes/app/_reglages.equipe_.inviter'
import { Route as AppReglagesParametresCreancierRouteImport } from './routes/app/_reglages.parametres_.creancier'
import { Route as AppReglagesParametresEtablissementRouteImport } from './routes/app/_reglages.parametres_.etablissement'
import { Route as AppCreanceIdIndexRouteImport } from './routes/app/creance.$id.index'
import { Route as AppCreanceIdDecompteRouteImport } from './routes/app/creance.$id.decompte'
import { Route as AppCreanceIdLitigeRouteImport } from './routes/app/creance.$id.litige'
import { Route as AppCreanceIdProcedureRouteImport } from './routes/app/creance.$id.procedure'
import { Route as AppCreanceIdRelancesRouteImport } from './routes/app/creance.$id.relances'
import { Route as AppCreanceIdRisquesRouteImport } from './routes/app/creance.$id.risques'
import { Route as AppCreanceIdSoliditeRouteImport } from './routes/app/creance.$id.solidite'
import { Route as AppDebiteursIdHabitudeRouteImport } from './routes/app/debiteurs.$id.habitude'
import { Route as AppDebiteursIdPiecesRouteImport } from './routes/app/debiteurs.$id.pieces'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveauMotDePasseRoute = NouveauMotDePasseRouteImport.update({
  id: '/nouveau-mot-de-passe',
  path: '/nouveau-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowroomRoute = ShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReglagesRoute = AppReglagesRouteImport.update({
  id: '/_reglages',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDebiteursRoute = AppDebiteursRouteImport.update({
  id: '/debiteurs',
  path: '/debiteurs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportFacturesRoute = AppImportFacturesRouteImport.update({
  id: '/import-factures',
  path: '/import-factures',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProceduresRoute = AppProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRevelationRoute = AppRevelationRouteImport.update({
  id: '/revelation',
  path: '/revelation',
  getParentRoute: () => AppRouteRoute,
} as any)
const RejoindreTokenRoute = RejoindreTokenRouteImport.update({
  id: '/rejoindre/$token',
  path: '/rejoindre/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReglagesAbonnementRoute = AppReglagesAbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => AppReglagesRoute,
} as any)
const AppReglagesDonneesRoute = AppReglagesDonneesRouteImport.update({
  id: '/donnees',
  path: '/donnees',
  getParentRoute: () => AppReglagesRoute,
} as any)
const AppReglagesEquipeRoute = AppReglagesEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppReglagesRoute,
} as any)
const AppReglagesParametresRoute = AppReglagesParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AppReglagesRoute,
} as any)
const AppCreanceIdRoute = AppCreanceIdRouteImport.update({
  id: '/creance/$id',
  path: '/creance/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDonneesSupprimerCompteRoute =
  AppDonneesSupprimerCompteRouteImport.update({
    id: '/donnees_/supprimer-compte',
    path: '/donnees/supprimer-compte',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppDonneesSupprimerEtablissementRoute =
  AppDonneesSupprimerEtablissementRouteImport.update({
    id: '/donnees_/supprimer-etablissement',
    path: '/donnees/supprimer-etablissement',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppImportFacturesIdRoute = AppImportFacturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppImportFacturesRoute,
} as any)
const AppReglagesAbonnementPremierBilanRoute =
  AppReglagesAbonnementPremierBilanRouteImport.update({
    id: '/abonnement_/premier-bilan',
    path: '/abonnement/premier-bilan',
    getParentRoute: () => AppReglagesRoute,
  } as any)
const AppReglagesAbonnementSuiviRoute =
  AppReglagesAbonnementSuiviRouteImport.update({
    id: '/abonnement_/suivi',
    path: '/abonnement/suivi',
    getParentRoute: () => AppReglagesRoute,
  } as any)
const AppReglagesDonneesExportRoute =
  AppReglagesDonneesExportRouteImport.update({
    id: '/donnees_/export',
    path: '/donnees/export',
    getParentRoute: () => AppReglagesRoute,
  } as any)
const AppReglagesEquipeInviterRoute =
  AppReglagesEquipeInviterRouteImport.update({
    id: '/equipe_/inviter',
    path: '/equipe/inviter',
    getParentRoute: () => AppReglagesRoute,
  } as any)
const AppReglagesParametresCreancierRoute =
  AppReglagesParametresCreancierRouteImport.update({
    id: '/parametres_/creancier',
    path: '/parametres/creancier',
    getParentRoute: () => AppReglagesRoute,
  } as any)
const AppReglagesParametresEtablissementRoute =
  AppReglagesParametresEtablissementRouteImport.update({
    id: '/parametres_/etablissement',
    path: '/parametres/etablissement',
    getParentRoute: () => AppReglagesRoute,
  } as any)
const AppCreanceIdIndexRoute = AppCreanceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCreanceIdRoute,
} as any)
const AppCreanceIdDecompteRoute = AppCreanceIdDecompteRouteImport.update({
  id: '/decompte',
  path: '/decompte',
  getParentRoute: () => AppCreanceIdRoute,
} as any)
const AppCreanceIdLitigeRoute = AppCreanceIdLitigeRouteImport.update({
  id: '/litige',
  path: '/litige',
  getParentRoute: () => AppCreanceIdRoute,
} as any)
const AppCreanceIdProcedureRoute = AppCreanceIdProcedureRouteImport.update({
  id: '/procedure',
  path: '/procedure',
  getParentRoute: () => AppCreanceIdRoute,
} as any)
const AppCreanceIdRelancesRoute = AppCreanceIdRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AppCreanceIdRoute,
} as any)
const AppCreanceIdRisquesRoute = AppCreanceIdRisquesRouteImport.update({
  id: '/risques',
  path: '/risques',
  getParentRoute: () => AppCreanceIdRoute,
} as any)
const AppCreanceIdSoliditeRoute = AppCreanceIdSoliditeRouteImport.update({
  id: '/solidite',
  path: '/solidite',
  getParentRoute: () => AppCreanceIdRoute,
} as any)
const AppDebiteursIdHabitudeRoute = AppDebiteursIdHabitudeRouteImport.update({
  id: '/$id/habitude',
  path: '/$id/habitude',
  getParentRoute: () => AppDebiteursRoute,
} as any)
const AppDebiteursIdPiecesRoute = AppDebiteursIdPiecesRouteImport.update({
  id: '/$id/pieces',
  path: '/$id/pieces',
  getParentRoute: () => AppDebiteursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/showroom': typeof ShowroomRoute
  '/app/debiteurs': typeof AppDebiteursRouteWithChildren
  '/app/import-factures': typeof AppImportFacturesRouteWithChildren
  '/app/procedures': typeof AppProceduresRoute
  '/app/revelation': typeof AppRevelationRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/abonnement': typeof AppReglagesAbonnementRoute
  '/app/donnees': typeof AppReglagesDonneesRoute
  '/app/equipe': typeof AppReglagesEquipeRoute
  '/app/parametres': typeof AppReglagesParametresRoute
  '/app/creance/$id': typeof AppCreanceIdRouteWithChildren
  '/app/donnees/supprimer-compte': typeof AppDonneesSupprimerCompteRoute
  '/app/donnees/supprimer-etablissement': typeof AppDonneesSupprimerEtablissementRoute
  '/app/import-factures/$id': typeof AppImportFacturesIdRoute
  '/app/abonnement/premier-bilan': typeof AppReglagesAbonnementPremierBilanRoute
  '/app/abonnement/suivi': typeof AppReglagesAbonnementSuiviRoute
  '/app/donnees/export': typeof AppReglagesDonneesExportRoute
  '/app/equipe/inviter': typeof AppReglagesEquipeInviterRoute
  '/app/parametres/creancier': typeof AppReglagesParametresCreancierRoute
  '/app/parametres/etablissement': typeof AppReglagesParametresEtablissementRoute
  '/app/creance/$id/decompte': typeof AppCreanceIdDecompteRoute
  '/app/creance/$id/litige': typeof AppCreanceIdLitigeRoute
  '/app/creance/$id/procedure': typeof AppCreanceIdProcedureRoute
  '/app/creance/$id/relances': typeof AppCreanceIdRelancesRoute
  '/app/creance/$id/risques': typeof AppCreanceIdRisquesRoute
  '/app/creance/$id/solidite': typeof AppCreanceIdSoliditeRoute
  '/app/debiteurs/$id/habitude': typeof AppDebiteursIdHabitudeRoute
  '/app/debiteurs/$id/pieces': typeof AppDebiteursIdPiecesRoute
  '/app/creance/$id/': typeof AppCreanceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/showroom': typeof ShowroomRoute
  '/app': typeof AppIndexRoute
  '/app/debiteurs': typeof AppDebiteursRouteWithChildren
  '/app/import-factures': typeof AppImportFacturesRouteWithChildren
  '/app/procedures': typeof AppProceduresRoute
  '/app/revelation': typeof AppRevelationRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/abonnement': typeof AppReglagesAbonnementRoute
  '/app/donnees': typeof AppReglagesDonneesRoute
  '/app/equipe': typeof AppReglagesEquipeRoute
  '/app/parametres': typeof AppReglagesParametresRoute
  '/app/donnees/supprimer-compte': typeof AppDonneesSupprimerCompteRoute
  '/app/donnees/supprimer-etablissement': typeof AppDonneesSupprimerEtablissementRoute
  '/app/import-factures/$id': typeof AppImportFacturesIdRoute
  '/app/abonnement/premier-bilan': typeof AppReglagesAbonnementPremierBilanRoute
  '/app/abonnement/suivi': typeof AppReglagesAbonnementSuiviRoute
  '/app/donnees/export': typeof AppReglagesDonneesExportRoute
  '/app/equipe/inviter': typeof AppReglagesEquipeInviterRoute
  '/app/parametres/creancier': typeof AppReglagesParametresCreancierRoute
  '/app/parametres/etablissement': typeof AppReglagesParametresEtablissementRoute
  '/app/creance/$id/decompte': typeof AppCreanceIdDecompteRoute
  '/app/creance/$id/litige': typeof AppCreanceIdLitigeRoute
  '/app/creance/$id/procedure': typeof AppCreanceIdProcedureRoute
  '/app/creance/$id/relances': typeof AppCreanceIdRelancesRoute
  '/app/creance/$id/risques': typeof AppCreanceIdRisquesRoute
  '/app/creance/$id/solidite': typeof AppCreanceIdSoliditeRoute
  '/app/debiteurs/$id/habitude': typeof AppDebiteursIdHabitudeRoute
  '/app/debiteurs/$id/pieces': typeof AppDebiteursIdPiecesRoute
  '/app/creance/$id': typeof AppCreanceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/bienvenue': typeof BienvenueRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveau-mot-de-passe': typeof NouveauMotDePasseRoute
  '/showroom': typeof ShowroomRoute
  '/app/_reglages': typeof AppReglagesRouteWithChildren
  '/app/debiteurs': typeof AppDebiteursRouteWithChildren
  '/app/import-factures': typeof AppImportFacturesRouteWithChildren
  '/app/procedures': typeof AppProceduresRoute
  '/app/revelation': typeof AppRevelationRoute
  '/rejoindre/$token': typeof RejoindreTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/_reglages/abonnement': typeof AppReglagesAbonnementRoute
  '/app/_reglages/donnees': typeof AppReglagesDonneesRoute
  '/app/_reglages/equipe': typeof AppReglagesEquipeRoute
  '/app/_reglages/parametres': typeof AppReglagesParametresRoute
  '/app/creance/$id': typeof AppCreanceIdRouteWithChildren
  '/app/donnees_/supprimer-compte': typeof AppDonneesSupprimerCompteRoute
  '/app/donnees_/supprimer-etablissement': typeof AppDonneesSupprimerEtablissementRoute
  '/app/import-factures/$id': typeof AppImportFacturesIdRoute
  '/app/_reglages/abonnement_/premier-bilan': typeof AppReglagesAbonnementPremierBilanRoute
  '/app/_reglages/abonnement_/suivi': typeof AppReglagesAbonnementSuiviRoute
  '/app/_reglages/donnees_/export': typeof AppReglagesDonneesExportRoute
  '/app/_reglages/equipe_/inviter': typeof AppReglagesEquipeInviterRoute
  '/app/_reglages/parametres_/creancier': typeof AppReglagesParametresCreancierRoute
  '/app/_reglages/parametres_/etablissement': typeof AppReglagesParametresEtablissementRoute
  '/app/creance/$id/decompte': typeof AppCreanceIdDecompteRoute
  '/app/creance/$id/litige': typeof AppCreanceIdLitigeRoute
  '/app/creance/$id/procedure': typeof AppCreanceIdProcedureRoute
  '/app/creance/$id/relances': typeof AppCreanceIdRelancesRoute
  '/app/creance/$id/risques': typeof AppCreanceIdRisquesRoute
  '/app/creance/$id/solidite': typeof AppCreanceIdSoliditeRoute
  '/app/debiteurs/$id/habitude': typeof AppDebiteursIdHabitudeRoute
  '/app/debiteurs/$id/pieces': typeof AppDebiteursIdPiecesRoute
  '/app/creance/$id/': typeof AppCreanceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bienvenue'
    | '/connexion'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/showroom'
    | '/app/debiteurs'
    | '/app/import-factures'
    | '/app/procedures'
    | '/app/revelation'
    | '/rejoindre/$token'
    | '/app/'
    | '/api/auth/$'
    | '/app/abonnement'
    | '/app/donnees'
    | '/app/equipe'
    | '/app/parametres'
    | '/app/creance/$id'
    | '/app/donnees/supprimer-compte'
    | '/app/donnees/supprimer-etablissement'
    | '/app/import-factures/$id'
    | '/app/abonnement/premier-bilan'
    | '/app/abonnement/suivi'
    | '/app/donnees/export'
    | '/app/equipe/inviter'
    | '/app/parametres/creancier'
    | '/app/parametres/etablissement'
    | '/app/creance/$id/decompte'
    | '/app/creance/$id/litige'
    | '/app/creance/$id/procedure'
    | '/app/creance/$id/relances'
    | '/app/creance/$id/risques'
    | '/app/creance/$id/solidite'
    | '/app/debiteurs/$id/habitude'
    | '/app/debiteurs/$id/pieces'
    | '/app/creance/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenue'
    | '/connexion'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/showroom'
    | '/app'
    | '/app/debiteurs'
    | '/app/import-factures'
    | '/app/procedures'
    | '/app/revelation'
    | '/rejoindre/$token'
    | '/api/auth/$'
    | '/app/abonnement'
    | '/app/donnees'
    | '/app/equipe'
    | '/app/parametres'
    | '/app/donnees/supprimer-compte'
    | '/app/donnees/supprimer-etablissement'
    | '/app/import-factures/$id'
    | '/app/abonnement/premier-bilan'
    | '/app/abonnement/suivi'
    | '/app/donnees/export'
    | '/app/equipe/inviter'
    | '/app/parametres/creancier'
    | '/app/parametres/etablissement'
    | '/app/creance/$id/decompte'
    | '/app/creance/$id/litige'
    | '/app/creance/$id/procedure'
    | '/app/creance/$id/relances'
    | '/app/creance/$id/risques'
    | '/app/creance/$id/solidite'
    | '/app/debiteurs/$id/habitude'
    | '/app/debiteurs/$id/pieces'
    | '/app/creance/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bienvenue'
    | '/connexion'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/nouveau-mot-de-passe'
    | '/showroom'
    | '/app/_reglages'
    | '/app/debiteurs'
    | '/app/import-factures'
    | '/app/procedures'
    | '/app/revelation'
    | '/rejoindre/$token'
    | '/app/'
    | '/api/auth/$'
    | '/app/_reglages/abonnement'
    | '/app/_reglages/donnees'
    | '/app/_reglages/equipe'
    | '/app/_reglages/parametres'
    | '/app/creance/$id'
    | '/app/donnees_/supprimer-compte'
    | '/app/donnees_/supprimer-etablissement'
    | '/app/import-factures/$id'
    | '/app/_reglages/abonnement_/premier-bilan'
    | '/app/_reglages/abonnement_/suivi'
    | '/app/_reglages/donnees_/export'
    | '/app/_reglages/equipe_/inviter'
    | '/app/_reglages/parametres_/creancier'
    | '/app/_reglages/parametres_/etablissement'
    | '/app/creance/$id/decompte'
    | '/app/creance/$id/litige'
    | '/app/creance/$id/procedure'
    | '/app/creance/$id/relances'
    | '/app/creance/$id/risques'
    | '/app/creance/$id/solidite'
    | '/app/debiteurs/$id/habitude'
    | '/app/debiteurs/$id/pieces'
    | '/app/creance/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  BienvenueRoute: typeof BienvenueRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NouveauMotDePasseRoute: typeof NouveauMotDePasseRoute
  ShowroomRoute: typeof ShowroomRoute
  RejoindreTokenRoute: typeof RejoindreTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveau-mot-de-passe': {
      id: '/nouveau-mot-de-passe'
      path: '/nouveau-mot-de-passe'
      fullPath: '/nouveau-mot-de-passe'
      preLoaderRoute: typeof NouveauMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showroom': {
      id: '/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof ShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_reglages': {
      id: '/app/_reglages'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppReglagesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/debiteurs': {
      id: '/app/debiteurs'
      path: '/debiteurs'
      fullPath: '/app/debiteurs'
      preLoaderRoute: typeof AppDebiteursRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import-factures': {
      id: '/app/import-factures'
      path: '/import-factures'
      fullPath: '/app/import-factures'
      preLoaderRoute: typeof AppImportFacturesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/procedures': {
      id: '/app/procedures'
      path: '/procedures'
      fullPath: '/app/procedures'
      preLoaderRoute: typeof AppProceduresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/revelation': {
      id: '/app/revelation'
      path: '/revelation'
      fullPath: '/app/revelation'
      preLoaderRoute: typeof AppRevelationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/rejoindre/$token': {
      id: '/rejoindre/$token'
      path: '/rejoindre/$token'
      fullPath: '/rejoindre/$token'
      preLoaderRoute: typeof RejoindreTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_reglages/abonnement': {
      id: '/app/_reglages/abonnement'
      path: '/abonnement'
      fullPath: '/app/abonnement'
      preLoaderRoute: typeof AppReglagesAbonnementRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/_reglages/donnees': {
      id: '/app/_reglages/donnees'
      path: '/donnees'
      fullPath: '/app/donnees'
      preLoaderRoute: typeof AppReglagesDonneesRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/_reglages/equipe': {
      id: '/app/_reglages/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppReglagesEquipeRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/_reglages/parametres': {
      id: '/app/_reglages/parametres'
      path: '/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppReglagesParametresRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/creance/$id': {
      id: '/app/creance/$id'
      path: '/creance/$id'
      fullPath: '/app/creance/$id'
      preLoaderRoute: typeof AppCreanceIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/donnees_/supprimer-compte': {
      id: '/app/donnees_/supprimer-compte'
      path: '/donnees/supprimer-compte'
      fullPath: '/app/donnees/supprimer-compte'
      preLoaderRoute: typeof AppDonneesSupprimerCompteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/donnees_/supprimer-etablissement': {
      id: '/app/donnees_/supprimer-etablissement'
      path: '/donnees/supprimer-etablissement'
      fullPath: '/app/donnees/supprimer-etablissement'
      preLoaderRoute: typeof AppDonneesSupprimerEtablissementRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import-factures/$id': {
      id: '/app/import-factures/$id'
      path: '/$id'
      fullPath: '/app/import-factures/$id'
      preLoaderRoute: typeof AppImportFacturesIdRouteImport
      parentRoute: typeof AppImportFacturesRoute
    }
    '/app/_reglages/abonnement_/premier-bilan': {
      id: '/app/_reglages/abonnement_/premier-bilan'
      path: '/abonnement/premier-bilan'
      fullPath: '/app/abonnement/premier-bilan'
      preLoaderRoute: typeof AppReglagesAbonnementPremierBilanRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/_reglages/abonnement_/suivi': {
      id: '/app/_reglages/abonnement_/suivi'
      path: '/abonnement/suivi'
      fullPath: '/app/abonnement/suivi'
      preLoaderRoute: typeof AppReglagesAbonnementSuiviRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/_reglages/donnees_/export': {
      id: '/app/_reglages/donnees_/export'
      path: '/donnees/export'
      fullPath: '/app/donnees/export'
      preLoaderRoute: typeof AppReglagesDonneesExportRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/_reglages/equipe_/inviter': {
      id: '/app/_reglages/equipe_/inviter'
      path: '/equipe/inviter'
      fullPath: '/app/equipe/inviter'
      preLoaderRoute: typeof AppReglagesEquipeInviterRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/_reglages/parametres_/creancier': {
      id: '/app/_reglages/parametres_/creancier'
      path: '/parametres/creancier'
      fullPath: '/app/parametres/creancier'
      preLoaderRoute: typeof AppReglagesParametresCreancierRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/_reglages/parametres_/etablissement': {
      id: '/app/_reglages/parametres_/etablissement'
      path: '/parametres/etablissement'
      fullPath: '/app/parametres/etablissement'
      preLoaderRoute: typeof AppReglagesParametresEtablissementRouteImport
      parentRoute: typeof AppReglagesRoute
    }
    '/app/creance/$id/': {
      id: '/app/creance/$id/'
      path: '/'
      fullPath: '/app/creance/$id/'
      preLoaderRoute: typeof AppCreanceIdIndexRouteImport
      parentRoute: typeof AppCreanceIdRoute
    }
    '/app/creance/$id/decompte': {
      id: '/app/creance/$id/decompte'
      path: '/decompte'
      fullPath: '/app/creance/$id/decompte'
      preLoaderRoute: typeof AppCreanceIdDecompteRouteImport
      parentRoute: typeof AppCreanceIdRoute
    }
    '/app/creance/$id/litige': {
      id: '/app/creance/$id/litige'
      path: '/litige'
      fullPath: '/app/creance/$id/litige'
      preLoaderRoute: typeof AppCreanceIdLitigeRouteImport
      parentRoute: typeof AppCreanceIdRoute
    }
    '/app/creance/$id/procedure': {
      id: '/app/creance/$id/procedure'
      path: '/procedure'
      fullPath: '/app/creance/$id/procedure'
      preLoaderRoute: typeof AppCreanceIdProcedureRouteImport
      parentRoute: typeof AppCreanceIdRoute
    }
    '/app/creance/$id/relances': {
      id: '/app/creance/$id/relances'
      path: '/relances'
      fullPath: '/app/creance/$id/relances'
      preLoaderRoute: typeof AppCreanceIdRelancesRouteImport
      parentRoute: typeof AppCreanceIdRoute
    }
    '/app/creance/$id/risques': {
      id: '/app/creance/$id/risques'
      path: '/risques'
      fullPath: '/app/creance/$id/risques'
      preLoaderRoute: typeof AppCreanceIdRisquesRouteImport
      parentRoute: typeof AppCreanceIdRoute
    }
    '/app/creance/$id/solidite': {
      id: '/app/creance/$id/solidite'
      path: '/solidite'
      fullPath: '/app/creance/$id/solidite'
      preLoaderRoute: typeof AppCreanceIdSoliditeRouteImport
      parentRoute: typeof AppCreanceIdRoute
    }
    '/app/debiteurs/$id/habitude': {
      id: '/app/debiteurs/$id/habitude'
      path: '/$id/habitude'
      fullPath: '/app/debiteurs/$id/habitude'
      preLoaderRoute: typeof AppDebiteursIdHabitudeRouteImport
      parentRoute: typeof AppDebiteursRoute
    }
    '/app/debiteurs/$id/pieces': {
      id: '/app/debiteurs/$id/pieces'
      path: '/$id/pieces'
      fullPath: '/app/debiteurs/$id/pieces'
      preLoaderRoute: typeof AppDebiteursIdPiecesRouteImport
      parentRoute: typeof AppDebiteursRoute
    }
  }
}

interface AppReglagesRouteChildren {
  AppReglagesAbonnementRoute: typeof AppReglagesAbonnementRoute
  AppReglagesDonneesRoute: typeof AppReglagesDonneesRoute
  AppReglagesEquipeRoute: typeof AppReglagesEquipeRoute
  AppReglagesParametresRoute: typeof AppReglagesParametresRoute
  AppReglagesAbonnementPremierBilanRoute: typeof AppReglagesAbonnementPremierBilanRoute
  AppReglagesAbonnementSuiviRoute: typeof AppReglagesAbonnementSuiviRoute
  AppReglagesDonneesExportRoute: typeof AppReglagesDonneesExportRoute
  AppReglagesEquipeInviterRoute: typeof AppReglagesEquipeInviterRoute
  AppReglagesParametresCreancierRoute: typeof AppReglagesParametresCreancierRoute
  AppReglagesParametresEtablissementRoute: typeof AppReglagesParametresEtablissementRoute
}

const AppReglagesRouteChildren: AppReglagesRouteChildren = {
  AppReglagesAbonnementRoute: AppReglagesAbonnementRoute,
  AppReglagesDonneesRoute: AppReglagesDonneesRoute,
  AppReglagesEquipeRoute: AppReglagesEquipeRoute,
  AppReglagesParametresRoute: AppReglagesParametresRoute,
  AppReglagesAbonnementPremierBilanRoute:
    AppReglagesAbonnementPremierBilanRoute,
  AppReglagesAbonnementSuiviRoute: AppReglagesAbonnementSuiviRoute,
  AppReglagesDonneesExportRoute: AppReglagesDonneesExportRoute,
  AppReglagesEquipeInviterRoute: AppReglagesEquipeInviterRoute,
  AppReglagesParametresCreancierRoute: AppReglagesParametresCreancierRoute,
  AppReglagesParametresEtablissementRoute:
    AppReglagesParametresEtablissementRoute,
}

const AppReglagesRouteWithChildren = AppReglagesRoute._addFileChildren(
  AppReglagesRouteChildren,
)

interface AppDebiteursRouteChildren {
  AppDebiteursIdHabitudeRoute: typeof AppDebiteursIdHabitudeRoute
  AppDebiteursIdPiecesRoute: typeof AppDebiteursIdPiecesRoute
}

const AppDebiteursRouteChildren: AppDebiteursRouteChildren = {
  AppDebiteursIdHabitudeRoute: AppDebiteursIdHabitudeRoute,
  AppDebiteursIdPiecesRoute: AppDebiteursIdPiecesRoute,
}

const AppDebiteursRouteWithChildren = AppDebiteursRoute._addFileChildren(
  AppDebiteursRouteChildren,
)

interface AppImportFacturesRouteChildren {
  AppImportFacturesIdRoute: typeof AppImportFacturesIdRoute
}

const AppImportFacturesRouteChildren: AppImportFacturesRouteChildren = {
  AppImportFacturesIdRoute: AppImportFacturesIdRoute,
}

const AppImportFacturesRouteWithChildren =
  AppImportFacturesRoute._addFileChildren(AppImportFacturesRouteChildren)

interface AppCreanceIdRouteChildren {
  AppCreanceIdDecompteRoute: typeof AppCreanceIdDecompteRoute
  AppCreanceIdLitigeRoute: typeof AppCreanceIdLitigeRoute
  AppCreanceIdProcedureRoute: typeof AppCreanceIdProcedureRoute
  AppCreanceIdRelancesRoute: typeof AppCreanceIdRelancesRoute
  AppCreanceIdRisquesRoute: typeof AppCreanceIdRisquesRoute
  AppCreanceIdSoliditeRoute: typeof AppCreanceIdSoliditeRoute
  AppCreanceIdIndexRoute: typeof AppCreanceIdIndexRoute
}

const AppCreanceIdRouteChildren: AppCreanceIdRouteChildren = {
  AppCreanceIdDecompteRoute: AppCreanceIdDecompteRoute,
  AppCreanceIdLitigeRoute: AppCreanceIdLitigeRoute,
  AppCreanceIdProcedureRoute: AppCreanceIdProcedureRoute,
  AppCreanceIdRelancesRoute: AppCreanceIdRelancesRoute,
  AppCreanceIdRisquesRoute: AppCreanceIdRisquesRoute,
  AppCreanceIdSoliditeRoute: AppCreanceIdSoliditeRoute,
  AppCreanceIdIndexRoute: AppCreanceIdIndexRoute,
}

const AppCreanceIdRouteWithChildren = AppCreanceIdRoute._addFileChildren(
  AppCreanceIdRouteChildren,
)

interface AppRouteRouteChildren {
  AppReglagesRoute: typeof AppReglagesRouteWithChildren
  AppDebiteursRoute: typeof AppDebiteursRouteWithChildren
  AppImportFacturesRoute: typeof AppImportFacturesRouteWithChildren
  AppProceduresRoute: typeof AppProceduresRoute
  AppRevelationRoute: typeof AppRevelationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCreanceIdRoute: typeof AppCreanceIdRouteWithChildren
  AppDonneesSupprimerCompteRoute: typeof AppDonneesSupprimerCompteRoute
  AppDonneesSupprimerEtablissementRoute: typeof AppDonneesSupprimerEtablissementRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppReglagesRoute: AppReglagesRouteWithChildren,
  AppDebiteursRoute: AppDebiteursRouteWithChildren,
  AppImportFacturesRoute: AppImportFacturesRouteWithChildren,
  AppProceduresRoute: AppProceduresRoute,
  AppRevelationRoute: AppRevelationRoute,
  AppIndexRoute: AppIndexRoute,
  AppCreanceIdRoute: AppCreanceIdRouteWithChildren,
  AppDonneesSupprimerCompteRoute: AppDonneesSupprimerCompteRoute,
  AppDonneesSupprimerEtablissementRoute: AppDonneesSupprimerEtablissementRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  BienvenueRoute: BienvenueRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NouveauMotDePasseRoute: NouveauMotDePasseRoute,
  ShowroomRoute: ShowroomRoute,
  RejoindreTokenRoute: RejoindreTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
